In [13]:
def product(N):
    mul=1
    for x in range(1,N+1):
        mul=mul*x
    return mul
product(4)




        

24

In [14]:
def Addition(N):
    total=0
    for x in range(1,N+1):
        total=total+x
    return total
Addition(4)


10

In [37]:
import numpy as np
mat =np.array( [[1 for x in range(5)] for y in range(5)] )

for x in range(5):
    for y in range(5):
        if x!=y:
            mat[x][y]=0
print (np.matrix(mat))


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [4]:
class Person_Details:
    def __init__(self):
        self.firstname="manogna"
        self.lastname="nallamothu"
        self.age=25


myperson=Person_Details()


print(myperson.firstname)

manogna


In [5]:
class Person_Details:
    def __init__(self,firstname,lastname):
        self.firstname=firstname
        self.lastname=lastname
        self.age=25


myperson=Person_Details("Teju","Yerroju")


print(myperson.firstname)

Teju


In [6]:
class Person_Details:
    def __init__(self,firstname="[no firstname]",lastname="[no lastname]"):
        self.firstname=firstname
        self.lastname=lastname
        self.age=25


myperson=Person_Details("Teju","Yerroju")

myperson1=Person_Details()


print(myperson.firstname)

print(myperson1.firstname)

Teju
[no firstname]


In [28]:
class circle:
    def __init__(self,radius):
        self.radius=radius
        
    def decrease(self):
        self.radius=self.radius-1
        return self.radius
    
    def perimeter(self):
        return (2*3.14*(self.radius))
    

circle1=circle(radius=1)

circle1.decrease()

circle1.perimeter()

#print (circle1.radius)

#print (circle1.area())

#print (circle1.permiter())

0.0